prebuilt_cxx_library(
    name = "libafl_c",
    header_dirs = ["include"],
    shared_lib = "//modules/libafl/rust:libafl-wrapper[cdylib]",
    soname = "liblibafl_c.so",
    preferred_linkage = "shared",
    visibility = ["PUBLIC"],
)
