// Generated by tracer::generate_decoder_source(). Do not edit.
//
// One struct per tracepoint of the objects this was generated from, and a
// decode() that turns a trace of those objects into those structs.
#pragma once

#include <algorithm>
#include <cstddef>
#include <cstdint>
#include <cstdlib>
#include <cstring>
#include <format>
#include <fstream>
#include <iterator>
#include <map>
#include <span>
#include <stdexcept>
#include <string>
#include <string_view>
#include <type_traits>
#include <utility>
#include <vector>

// mmap and friends. The objects a decode reads are big -- half a gigabyte for a
// Scylla build with its debug info -- and it touches a few kilobytes of each, so
// they are mapped rather than read. Linux only, like the tracer itself.
#include <fcntl.h>
#include <sys/mman.h>
#include <sys/stat.h>
#include <unistd.h>

namespace trace {

// Which tracepoint a record came from, and when it was taken. Everything but
// the timestamp is a fact about the call site, fixed at compile time.
struct tracepoint_metadata {
    std::string_view name;
    std::string_view file;
    int line;
    std::string_view function;
    std::uint64_t timestamp;
};

namespace detail {

// Every read is bounded by the end of the trace. A record is not
// self-delimiting, so a truncated one cannot be recognised as short until a
// field runs off the end -- and a field that ran off the end must be an
// exception rather than a view into whatever follows the buffer.
inline void require(const std::byte* p, const std::byte* end, std::size_t n) {
    if (static_cast<std::size_t>(end - p) < n) {
        throw std::runtime_error(
            std::format("truncated trace: {} bytes left, {} wanted", end - p, n));
    }
}

template <typename To>
    requires std::is_trivially_copyable_v<To>
To read_unaligned(const std::byte*& p, const std::byte* end) {
    require(p, end, sizeof(To));
    To dst;
    std::memcpy(&dst, p, sizeof(To));
    p += sizeof(To);
    return dst;
}

// Length-prefixed runs. Both views point into the trace buffer rather than
// copying out of it, which is what keeps decoding allocation-free -- and what
// makes them valid only as long as that buffer is.
inline std::span<const std::byte> read_bytes(const std::byte*& p, const std::byte* end) {
    const auto len = read_unaligned<std::uint16_t>(p, end);
    require(p, end, len);
    const std::span<const std::byte> out(p, len);
    p += len;
    return out;
}

inline std::string_view read_str(const std::byte*& p, const std::byte* end) {
    const std::span<const std::byte> raw = read_bytes(p, end);
    return {reinterpret_cast<const char*>(raw.data()), raw.size()};
}

// How to_string() renders one field. Free functions rather than a formatter
// specialisation, so that a caller printing a field itself can reach for the
// same rendering without adopting it for every std::span in its program.
inline std::string field_to_string(std::span<const std::byte> v) {
    std::string out;
    for (std::byte b : v) {
        out += std::format("{:02x}", std::to_integer<unsigned>(b));
    }
    return out;
}

inline std::string field_to_string(std::string_view v) { return std::string(v); }

inline std::string field_to_string(const void* v) { return std::format("{}", v); }

template <typename T>
std::string field_to_string(const T& v) {
    return std::format("{}", v);
}

}  // namespace detail

// --- resolving a source location ----------------------------------------------
//
// A srcloc::location on the wire is one address, and nothing else: the address
// of a constant the compiler laid down in the object that captured it. Reading
// it back is three steps.
//
//   1. Which object was it in? The metadata stream says where each object was
//      mapped -- its base and how far it reached -- as of the moment the record
//      was written, so this is the same "read the mappings at that timestamp"
//      lookup a tracepoint address goes through, against a different range.
//   2. Subtract the base. What is left is a virtual address in the object's own
//      link-time layout, which is a fact about the *file* rather than the run.
//   3. Open the file and read it. The object is found by build ID, in the
//      directory laid out below; the location is the four fields of a
//      std::source_location, and the two of them that are pointers are more
//      virtual addresses in the same object, read the same way.
//
// A location that cannot be taken through all three -- an object the directory
// does not have, a run recorded before it was mapped -- comes out unresolved
// rather than wrong, with the address it was recorded as. See resolved below.

// One decoded source location. Owning strings rather than views into the object
// file, so that an event outlives the dso_directory it was resolved against;
// everything else a decoded event holds points into the trace, and this is the
// one field that would otherwise point somewhere with a shorter life.
struct source_location {
    std::string file;
    std::string function;
    std::uint32_t line = 0;
    std::uint32_t column = 0;

    std::uint64_t address = 0;  // as recorded, and all there is if !resolved
    std::string object;         // build ID of the object it was found in
    bool resolved = false;

    [[nodiscard]] std::string to_string() const {
        if (resolved) {
            return std::format("{}:{}:{}", file, line, column);
        }
        if (address == 0) {
            return "<none>";  // srcloc::location::none(), recorded as it was
        }
        return std::format("<unresolved {:#x}>", address);
    }
};

namespace detail {

// Where a link-time virtual address lands in the object's file, or nullptr if
// it lands nowhere that has `size` bytes behind it.
//
// The ELF header and program headers are read by offset rather than through
// <elf.h>, so that a decoder built anywhere can read a trace from a Linux
// x86-64 program -- which is the only kind there is. Anything that is not a
// little-endian 64-bit ELF is refused rather than misread.
[[nodiscard]] inline const std::byte* at_vaddr(std::span<const std::byte> image,
                                               std::uint64_t vaddr, std::size_t size) {
    constexpr std::size_t e_phoff_at = 0x20;
    constexpr std::size_t e_phentsize_at = 0x36;
    constexpr std::size_t e_phnum_at = 0x38;
    constexpr std::uint32_t pt_load = 1;

    const auto word = [image](std::size_t at, std::size_t width) -> std::uint64_t {
        std::uint64_t value = 0;
        std::memcpy(&value, image.data() + at, width);
        return value;
    };
    const auto fits = [image](std::size_t at, std::size_t width) {
        return at + width <= image.size();
    };

    if (!fits(0, 0x40) || std::memcmp(image.data(), "\x7f" "ELF\x02\x01", 6) != 0) {
        return nullptr;
    }
    const std::uint64_t phoff = word(e_phoff_at, 8);
    const std::uint64_t phentsize = word(e_phentsize_at, 2);
    const std::uint64_t phnum = word(e_phnum_at, 2);

    for (std::uint64_t i = 0; i < phnum; ++i) {
        const auto at = static_cast<std::size_t>(phoff + i * phentsize);
        if (!fits(at, 56)) {
            return nullptr;
        }
        if (word(at, 4) != pt_load) {
            continue;
        }
        const std::uint64_t p_offset = word(at + 8, 8);
        const std::uint64_t p_vaddr = word(at + 16, 8);
        const std::uint64_t p_filesz = word(at + 32, 8);
        if (vaddr < p_vaddr || vaddr - p_vaddr >= p_filesz) {
            continue;
        }
        // A .bss address is in the segment's memory size but not its file size,
        // and has nothing behind it to read.
        const std::uint64_t offset = p_offset + (vaddr - p_vaddr);
        if (!fits(static_cast<std::size_t>(offset), size)) {
            return nullptr;
        }
        return image.data() + offset;
    }
    return nullptr;
}

// One object file, mapped rather than read into memory.
//
// These are big -- a Scylla binary with its debug info is half a gigabyte -- and
// a decode touches a few kilobytes of each: the program headers, the dynamic
// relocations, and whatever strings the locations point at. Reading the whole
// file in to look at that copies the entire object for nothing, and pins it in
// the heap for as long as the decoder lives. Mapping hands out the same
// std::span and lets the kernel fault in only the pages actually touched.
class mapped_file {
public:
    mapped_file() = default;

    explicit mapped_file(const std::string& path) {
        const int fd = ::open(path.c_str(), O_RDONLY | O_CLOEXEC);
        if (fd < 0) {
            return;
        }
        struct ::stat info {};
        if (::fstat(fd, &info) == 0 && info.st_size > 0) {
            void* const p = ::mmap(nullptr, static_cast<std::size_t>(info.st_size), PROT_READ,
                                   MAP_PRIVATE, fd, 0);
            if (p != MAP_FAILED) {
                data_ = static_cast<const std::byte*>(p);
                size_ = static_cast<std::size_t>(info.st_size);
            }
        }
        // The mapping holds its own reference to the file, so the descriptor is
        // not wanted past here -- and a decoder that mapped a dozen objects
        // would otherwise sit on a dozen descriptors for its whole life.
        ::close(fd);
    }

    ~mapped_file() {
        if (data_ != nullptr) {
            ::munmap(const_cast<std::byte*>(data_), size_);
        }
    }

    mapped_file(mapped_file&& other) noexcept : data_(other.data_), size_(other.size_) {
        other.data_ = nullptr;
        other.size_ = 0;
    }

    mapped_file& operator=(mapped_file&& other) noexcept {
        if (this != &other) {
            if (data_ != nullptr) {
                ::munmap(const_cast<std::byte*>(data_), size_);
            }
            data_ = other.data_;
            size_ = other.size_;
            other.data_ = nullptr;
            other.size_ = 0;
        }
        return *this;
    }

    mapped_file(const mapped_file&) = delete;
    mapped_file& operator=(const mapped_file&) = delete;

    [[nodiscard]] bool ok() const { return data_ != nullptr; }
    [[nodiscard]] std::span<const std::byte> bytes() const { return {data_, size_}; }

private:
    const std::byte* data_ = nullptr;
    std::size_t size_ = 0;
};

// The relative relocations of one object, as (place, value) pairs sorted by
// place -- both link-time virtual addresses.
//
// A pointer stored inside a shared object is not in the object's file. x86-64
// uses RELA, whose addend lives in the relocation entry rather than at the place
// it patches, so the file holds a zero there and the value is only in
// .rela.dyn; the loader writes it as the object is mapped. The two pointers of a
// source location -- its file and its function -- are exactly that, so a decoder
// reading them straight out of the image would get nothing but a zero, and
// resolve every location in every shared library to the same wrong thing.
//
// Only R_X86_64_RELATIVE is collected, which is what a pointer to something in
// the same object is. DT_RELR needs nothing here: it packs offsets and leaves
// the value in place, so the file already holds it.
//
// An object with no dynamic segment -- a non-PIE executable is the usual one --
// has no such relocations and needs none: its pointers are absolute and already
// written down.
[[nodiscard]] inline std::vector<std::pair<std::uint64_t, std::uint64_t>> relative_relocations(
    std::span<const std::byte> image) {
    constexpr std::size_t e_phoff_at = 0x20;
    constexpr std::size_t e_phentsize_at = 0x36;
    constexpr std::size_t e_phnum_at = 0x38;
    constexpr std::uint32_t pt_dynamic = 2;
    constexpr std::uint64_t dt_null = 0;
    constexpr std::uint64_t dt_rela = 7;
    constexpr std::uint64_t dt_relasz = 8;
    constexpr std::uint64_t dt_relaent = 9;
    constexpr std::uint32_t r_x86_64_relative = 8;

    std::vector<std::pair<std::uint64_t, std::uint64_t>> out;
    const auto word = [image](std::size_t at, std::size_t width) -> std::uint64_t {
        std::uint64_t value = 0;
        std::memcpy(&value, image.data() + at, width);
        return value;
    };
    if (image.size() < 0x40 || std::memcmp(image.data(), "\x7f" "ELF\x02\x01", 6) != 0) {
        return out;
    }
    const std::uint64_t phoff = word(e_phoff_at, 8);
    const std::uint64_t phentsize = word(e_phentsize_at, 2);
    const std::uint64_t phnum = word(e_phnum_at, 2);

    std::uint64_t dynamic_at = 0;
    std::uint64_t dynamic_size = 0;
    for (std::uint64_t i = 0; i < phnum; ++i) {
        const auto at = static_cast<std::size_t>(phoff + i * phentsize);
        if (at + 56 > image.size()) {
            return out;
        }
        if (word(at, 4) == pt_dynamic) {
            dynamic_at = word(at + 16, 8);   // p_vaddr
            dynamic_size = word(at + 40, 8); // p_memsz
        }
    }
    const std::byte* const dynamic = at_vaddr(image, dynamic_at, static_cast<std::size_t>(dynamic_size));
    if (dynamic == nullptr) {
        return out;
    }

    std::uint64_t rela = 0;
    std::uint64_t relasz = 0;
    std::uint64_t relaent = 24;
    for (std::uint64_t at = 0; at + 16 <= dynamic_size; at += 16) {
        std::uint64_t tag = 0;
        std::uint64_t value = 0;
        std::memcpy(&tag, dynamic + at, sizeof(tag));
        std::memcpy(&value, dynamic + at + 8, sizeof(value));
        if (tag == dt_null) {
            break;
        }
        if (tag == dt_rela) rela = value;
        if (tag == dt_relasz) relasz = value;
        if (tag == dt_relaent && value != 0) relaent = value;
    }
    if (rela == 0 || relasz == 0) {
        return out;
    }
    const std::byte* const entries = at_vaddr(image, rela, static_cast<std::size_t>(relasz));
    if (entries == nullptr) {
        return out;
    }
    for (std::uint64_t at = 0; at + 24 <= relasz; at += relaent) {
        std::uint64_t place = 0;
        std::uint64_t info = 0;
        std::uint64_t addend = 0;
        std::memcpy(&place, entries + at, sizeof(place));
        std::memcpy(&info, entries + at + 8, sizeof(info));
        std::memcpy(&addend, entries + at + 16, sizeof(addend));
        if (static_cast<std::uint32_t>(info) == r_x86_64_relative) {
            out.emplace_back(place, addend);
        }
    }
    std::sort(out.begin(), out.end());
    return out;
}

// The value a pointer field holds once the loader has been through it: what is
// written at `place` in the file, or the relocation's addend where the file
// holds nothing.
[[nodiscard]] inline std::uint64_t relocated(
    const std::vector<std::pair<std::uint64_t, std::uint64_t>>& relocations, std::uint64_t place,
    std::uint64_t in_file) {
    if (in_file != 0) {
        return in_file;
    }
    const auto found = std::lower_bound(relocations.begin(), relocations.end(),
                                        std::pair<std::uint64_t, std::uint64_t>{place, 0});
    return found != relocations.end() && found->first == place ? found->second : in_file;
}

}  // namespace detail

// The objects a trace needs to be decoded against, by build ID.
//
//     <root>/.build-id/<first two hex digits>/<the rest>[.debug]
//
// which is the layout gdb and llvm-cov already expect from a
// --debug-file-directory, and what tracer::write_dso_directory() produces. The
// whole file is read rather than mapped: a decode reads a handful of scattered
// words out of each object, and a lifetime that ends when this object does is
// worth more here than the pages saved.
class dso_directory {
public:
    explicit dso_directory(std::string root) : root_(std::move(root)) {}

    // Where a decoder looks when its caller says nothing: $TRACE_DSO_DIR, or the
    // working directory.
    dso_directory() {
        const char* const from_env = std::getenv("TRACE_DSO_DIR");
        root_ = from_env != nullptr ? from_env : ".";
    }

    // The object's bytes, or an empty span if the directory does not have it.
    // Misses are remembered too: a trace holds many records from one object, and
    // a missing object should be one failed open rather than thousands.
    [[nodiscard]] std::span<const std::byte> object(const std::string& build_id) {
        const auto found = files_.find(build_id);
        if (found != files_.end()) {
            return found->second.bytes();
        }
        detail::mapped_file image;
        if (build_id.size() >= 3) {
            const std::string stem =
                root_ + "/.build-id/" + build_id.substr(0, 2) + "/" + build_id.substr(2);
            // With the suffix first, because that is what a debuginfo directory
            // holds; without it for a directory of plain binaries.
            for (const std::string& path : {stem + ".debug", stem}) {
                detail::mapped_file candidate(path);
                if (candidate.ok()) {
                    image = std::move(candidate);
                    break;
                }
            }
        }
        return files_.emplace(build_id, std::move(image)).first->second.bytes();
    }

    // Where the object's file is, or an empty string if the directory does not
    // have it. For handing to something that reads objects itself -- addr2line
    // over a stack of frames, say -- rather than for reading here.
    [[nodiscard]] std::string path(const std::string& build_id) const {
        if (build_id.size() < 3) {
            return {};
        }
        const std::string stem =
            root_ + "/.build-id/" + build_id.substr(0, 2) + "/" + build_id.substr(2);
        // Same two candidates, in the same order, as object() above.
        for (const std::string& candidate : {stem + ".debug", stem}) {
            if (std::ifstream(candidate, std::ios::binary)) {
                return candidate;
            }
        }
        return {};
    }

    // The object's relative relocations, read once. A location's file and
    // function pointers are not in the file of a shared object -- see
    // detail::relative_relocations() -- and a trace holds a location per record,
    // so this is built on first use and kept.
    [[nodiscard]] const std::vector<std::pair<std::uint64_t, std::uint64_t>>& relocations(
        const std::string& build_id) {
        const auto found = relocations_.find(build_id);
        if (found != relocations_.end()) {
            return found->second;
        }
        return relocations_.emplace(build_id, detail::relative_relocations(object(build_id)))
            .first->second;
    }

private:
    std::string root_;
    std::map<std::string, detail::mapped_file, std::less<>> files_;
    std::map<std::string, std::vector<std::pair<std::uint64_t, std::uint64_t>>, std::less<>>
        relocations_;
};

// The directory a decode uses when its caller names none. One per process, so
// that a program decoding several traces reads each object once; a caller that
// wants a directory of its own passes it to decode() instead.
[[nodiscard]] inline dso_directory& shared_dso_directory() {
    static dso_directory directory;
    return directory;
}

namespace detail {

// How to_string() renders a location, beside the other field renderings above.
inline std::string field_to_string(const source_location& v) { return v.to_string(); }

// A NUL-terminated string at a virtual address, bounded by the end of the file:
// an object naming a location it does not hold is a corrupt object, not a read
// off the end of one.
[[nodiscard]] inline std::string string_at_vaddr(std::span<const std::byte> image,
                                                 std::uint64_t vaddr) {
    const std::byte* const p = at_vaddr(image, vaddr, 1);
    if (p == nullptr) {
        return {};
    }
    const auto* text = reinterpret_cast<const char*>(p);
    const std::size_t room = image.size() - static_cast<std::size_t>(p - image.data());
    const void* const nul = std::memchr(text, '\0', room);
    return nul == nullptr ? std::string{} : std::string(text);
}

}  // namespace detail

// /home/michal/projects/cpp_template/modules/tracer/include/tracer/tracer.h:1127
struct clock_sync {
    std::uint64_t realtime_ns;
    std::uint64_t ticks_per_second;

    [[nodiscard]] std::string to_string() const {
        return std::format("clock_sync{{realtime_ns={}, ticks_per_second={}}}",
                           detail::field_to_string(realtime_ns),
                           detail::field_to_string(ticks_per_second));
    }
};

// seastar/src/core/scylla_tracer.cc:115
struct run_task {
    std::uint64_t prev;
    std::uint64_t task;
    source_location at;

    [[nodiscard]] std::string to_string() const {
        return std::format("run_task{{prev={}, task={}, at={}}}",
                           detail::field_to_string(prev),
                           detail::field_to_string(task),
                           detail::field_to_string(at));
    }
};

// seastar/src/core/scylla_tracer.cc:120
struct execution_stage {
    std::uint64_t prev;
    std::uint64_t task;

    [[nodiscard]] std::string to_string() const {
        return std::format("execution_stage{{prev={}, task={}}}",
                           detail::field_to_string(prev),
                           detail::field_to_string(task));
    }
};

// seastar/src/core/scylla_tracer.cc:125
struct cql_request {
    std::uint64_t prev;
    std::uint64_t task;

    [[nodiscard]] std::string to_string() const {
        return std::format("cql_request{{prev={}, task={}}}",
                           detail::field_to_string(prev),
                           detail::field_to_string(task));
    }
};

// seastar/src/core/scylla_tracer.cc:130
struct semaphore_execute {
    std::uint64_t prev;
    std::uint64_t task;

    [[nodiscard]] std::string to_string() const {
        return std::format("semaphore_execute{{prev={}, task={}}}",
                           detail::field_to_string(prev),
                           detail::field_to_string(task));
    }
};

// seastar/src/core/scylla_tracer.cc:135
struct io_begin {
    std::uint64_t task;
    std::uint64_t io;

    [[nodiscard]] std::string to_string() const {
        return std::format("io_begin{{task={}, io={}}}",
                           detail::field_to_string(task),
                           detail::field_to_string(io));
    }
};

// seastar/src/core/scylla_tracer.cc:140
struct io_end {
    std::uint64_t task;
    std::uint64_t io;

    [[nodiscard]] std::string to_string() const {
        return std::format("io_end{{task={}, io={}}}",
                           detail::field_to_string(task),
                           detail::field_to_string(io));
    }
};

// seastar/src/core/scylla_tracer.cc:147
struct prepared_statement_added {
    std::string_view keyspace;
    std::string_view statement;
    std::span<const std::byte> id;

    [[nodiscard]] std::string to_string() const {
        return std::format("prepared_statement_added{{keyspace={}, statement={}, id={}}}",
                           detail::field_to_string(keyspace),
                           detail::field_to_string(statement),
                           detail::field_to_string(id));
    }
};

// seastar/src/core/scylla_tracer.cc:154
struct prepared_statement_removed {
    std::string_view keyspace;
    std::string_view statement;
    std::span<const std::byte> id;

    [[nodiscard]] std::string to_string() const {
        return std::format("prepared_statement_removed{{keyspace={}, statement={}, id={}}}",
                           detail::field_to_string(keyspace),
                           detail::field_to_string(statement),
                           detail::field_to_string(id));
    }
};

// seastar/src/core/scylla_tracer.cc:159
struct prepared_query_run {
    std::span<const std::byte> id;

    [[nodiscard]] std::string to_string() const {
        return std::format("prepared_query_run{{id={}}}",
                           detail::field_to_string(id));
    }
};

// seastar/src/core/scylla_tracer.cc:164
struct prepared_statements_snapshot_begin {
    [[nodiscard]] std::string to_string() const {
        return std::format("prepared_statements_snapshot_begin{{}}");
    }
};

// seastar/src/core/scylla_tracer.cc:171
struct prepared_statement_snapshot_entry {
    std::string_view keyspace;
    std::string_view statement;
    std::span<const std::byte> id;

    [[nodiscard]] std::string to_string() const {
        return std::format("prepared_statement_snapshot_entry{{keyspace={}, statement={}, id={}}}",
                           detail::field_to_string(keyspace),
                           detail::field_to_string(statement),
                           detail::field_to_string(id));
    }
};

// seastar/src/core/scylla_tracer.cc:176
struct prepared_statements_snapshot_end {
    [[nodiscard]] std::string to_string() const {
        return std::format("prepared_statements_snapshot_end{{}}");
    }
};

// seastar/src/core/scylla_tracer.cc:190
struct rpc_connection_open {
    std::uint64_t connection;
    std::string_view local;
    std::string_view remote;

    [[nodiscard]] std::string to_string() const {
        return std::format("rpc_connection_open{{connection={}, local={}, remote={}}}",
                           detail::field_to_string(connection),
                           detail::field_to_string(local),
                           detail::field_to_string(remote));
    }
};

// seastar/src/core/scylla_tracer.cc:201
struct rpc_connection_close {
    std::uint64_t connection;

    [[nodiscard]] std::string to_string() const {
        return std::format("rpc_connection_close{{connection={}}}",
                           detail::field_to_string(connection));
    }
};

// seastar/src/core/scylla_tracer.cc:209
struct rpc_message_sent {
    std::uint64_t connection;
    std::uint64_t sequence;
    std::uint64_t task;

    [[nodiscard]] std::string to_string() const {
        return std::format("rpc_message_sent{{connection={}, sequence={}, task={}}}",
                           detail::field_to_string(connection),
                           detail::field_to_string(sequence),
                           detail::field_to_string(task));
    }
};

// seastar/src/core/scylla_tracer.cc:215
struct rpc_message_received {
    std::uint64_t connection;
    std::uint64_t sequence;

    [[nodiscard]] std::string to_string() const {
        return std::format("rpc_message_received{{connection={}, sequence={}}}",
                           detail::field_to_string(connection),
                           detail::field_to_string(sequence));
    }
};

// seastar/src/core/scylla_tracer.cc:222
struct rpc_reply_sent {
    std::uint64_t connection;
    std::uint64_t sequence;
    std::int64_t msg_id;
    std::uint64_t task;

    [[nodiscard]] std::string to_string() const {
        return std::format("rpc_reply_sent{{connection={}, sequence={}, msg_id={}, task={}}}",
                           detail::field_to_string(connection),
                           detail::field_to_string(sequence),
                           detail::field_to_string(msg_id),
                           detail::field_to_string(task));
    }
};

// seastar/src/core/scylla_tracer.cc:228
struct rpc_reply_received {
    std::uint64_t connection;
    std::uint64_t sequence;
    std::int64_t msg_id;

    [[nodiscard]] std::string to_string() const {
        return std::format("rpc_reply_received{{connection={}, sequence={}, msg_id={}}}",
                           detail::field_to_string(connection),
                           detail::field_to_string(sequence),
                           detail::field_to_string(msg_id));
    }
};

// seastar/src/core/scylla_tracer.cc:235
struct rpc_connections_snapshot_begin {
    [[nodiscard]] std::string to_string() const {
        return std::format("rpc_connections_snapshot_begin{{}}");
    }
};

// seastar/src/core/scylla_tracer.cc:237
struct rpc_connection_snapshot_entry {
    std::uint64_t connection;
    std::string_view local;
    std::string_view remote;

    [[nodiscard]] std::string to_string() const {
        return std::format("rpc_connection_snapshot_entry{{connection={}, local={}, remote={}}}",
                           detail::field_to_string(connection),
                           detail::field_to_string(local),
                           detail::field_to_string(remote));
    }
};

// seastar/src/core/scylla_tracer.cc:241
struct rpc_connections_snapshot_end {
    [[nodiscard]] std::string to_string() const {
        return std::format("rpc_connections_snapshot_end{{}}");
    }
};

// seastar/src/core/scylla_tracer.cc:249
struct rpc_request_handled {
    std::uint64_t connection;
    std::uint64_t sequence;
    std::uint64_t prev;
    std::uint64_t task;

    [[nodiscard]] std::string to_string() const {
        return std::format("rpc_request_handled{{connection={}, sequence={}, prev={}, task={}}}",
                           detail::field_to_string(connection),
                           detail::field_to_string(sequence),
                           detail::field_to_string(prev),
                           detail::field_to_string(task));
    }
};

// /home/michal/projects/cpp_template/modules/tracer/include/tracer/tracer.h:1153
struct trace_objects_loaded {
    std::uint32_t count;

    [[nodiscard]] std::string to_string() const {
        return std::format("trace_objects_loaded{{count={}}}",
                           detail::field_to_string(count));
    }
};

// /home/michal/projects/cpp_template/modules/tracer/include/tracer/tracer.h:1168
struct trace_object_unloaded {
    std::string_view build_id;
    std::uint64_t base_address;

    [[nodiscard]] std::string to_string() const {
        return std::format("trace_object_unloaded{{build_id={}, base_address={}}}",
                           detail::field_to_string(build_id),
                           detail::field_to_string(base_address));
    }
};

// /home/michal/projects/cpp_template/modules/tracer/include/tracer/tracer.h:1181
struct trace_object_loaded {
    std::string_view build_id;
    std::uint64_t table_address;
    std::uint64_t base_address;
    std::uint64_t mapping_size;

    [[nodiscard]] std::string to_string() const {
        return std::format("trace_object_loaded{{build_id={}, table_address={}, base_address={}, mapping_size={}}}",
                           detail::field_to_string(build_id),
                           detail::field_to_string(table_address),
                           detail::field_to_string(base_address),
                           detail::field_to_string(mapping_size));
    }
};

// seastar/src/core/scylla_stacktrace_sampler.cc:82
struct stacktrace_sample {
    std::uint32_t shard;
    std::uint64_t time_ns;
    std::span<const std::byte> frames;

    [[nodiscard]] std::string to_string() const {
        return std::format("stacktrace_sample{{shard={}, time_ns={}, frames={}}}",
                           detail::field_to_string(shard),
                           detail::field_to_string(time_ns),
                           detail::field_to_string(frames));
    }
};

namespace detail {

inline clock_sync read_clock_sync(const std::byte*& p, const std::byte* end) {
    clock_sync out{};
    out.realtime_ns = detail::read_unaligned<std::uint64_t>(p, end);
    out.ticks_per_second = detail::read_unaligned<std::uint64_t>(p, end);
    return out;
}

inline run_task read_run_task(const std::byte*& p, const std::byte* end) {
    run_task out{};
    out.prev = detail::read_unaligned<std::uint64_t>(p, end);
    out.task = detail::read_unaligned<std::uint64_t>(p, end);
    out.at.address = detail::read_unaligned<std::uint64_t>(p, end);
    return out;
}

inline execution_stage read_execution_stage(const std::byte*& p, const std::byte* end) {
    execution_stage out{};
    out.prev = detail::read_unaligned<std::uint64_t>(p, end);
    out.task = detail::read_unaligned<std::uint64_t>(p, end);
    return out;
}

inline cql_request read_cql_request(const std::byte*& p, const std::byte* end) {
    cql_request out{};
    out.prev = detail::read_unaligned<std::uint64_t>(p, end);
    out.task = detail::read_unaligned<std::uint64_t>(p, end);
    return out;
}

inline semaphore_execute read_semaphore_execute(const std::byte*& p, const std::byte* end) {
    semaphore_execute out{};
    out.prev = detail::read_unaligned<std::uint64_t>(p, end);
    out.task = detail::read_unaligned<std::uint64_t>(p, end);
    return out;
}

inline io_begin read_io_begin(const std::byte*& p, const std::byte* end) {
    io_begin out{};
    out.task = detail::read_unaligned<std::uint64_t>(p, end);
    out.io = detail::read_unaligned<std::uint64_t>(p, end);
    return out;
}

inline io_end read_io_end(const std::byte*& p, const std::byte* end) {
    io_end out{};
    out.task = detail::read_unaligned<std::uint64_t>(p, end);
    out.io = detail::read_unaligned<std::uint64_t>(p, end);
    return out;
}

inline prepared_statement_added read_prepared_statement_added(const std::byte*& p, const std::byte* end) {
    prepared_statement_added out{};
    out.keyspace = detail::read_str(p, end);
    out.statement = detail::read_str(p, end);
    out.id = detail::read_bytes(p, end);
    return out;
}

inline prepared_statement_removed read_prepared_statement_removed(const std::byte*& p, const std::byte* end) {
    prepared_statement_removed out{};
    out.keyspace = detail::read_str(p, end);
    out.statement = detail::read_str(p, end);
    out.id = detail::read_bytes(p, end);
    return out;
}

inline prepared_query_run read_prepared_query_run(const std::byte*& p, const std::byte* end) {
    prepared_query_run out{};
    out.id = detail::read_bytes(p, end);
    return out;
}

inline prepared_statements_snapshot_begin read_prepared_statements_snapshot_begin([[maybe_unused]] const std::byte*& p, [[maybe_unused]] const std::byte* end) {
    prepared_statements_snapshot_begin out{};
    return out;
}

inline prepared_statement_snapshot_entry read_prepared_statement_snapshot_entry(const std::byte*& p, const std::byte* end) {
    prepared_statement_snapshot_entry out{};
    out.keyspace = detail::read_str(p, end);
    out.statement = detail::read_str(p, end);
    out.id = detail::read_bytes(p, end);
    return out;
}

inline prepared_statements_snapshot_end read_prepared_statements_snapshot_end([[maybe_unused]] const std::byte*& p, [[maybe_unused]] const std::byte* end) {
    prepared_statements_snapshot_end out{};
    return out;
}

inline rpc_connection_open read_rpc_connection_open(const std::byte*& p, const std::byte* end) {
    rpc_connection_open out{};
    out.connection = detail::read_unaligned<std::uint64_t>(p, end);
    out.local = detail::read_str(p, end);
    out.remote = detail::read_str(p, end);
    return out;
}

inline rpc_connection_close read_rpc_connection_close(const std::byte*& p, const std::byte* end) {
    rpc_connection_close out{};
    out.connection = detail::read_unaligned<std::uint64_t>(p, end);
    return out;
}

inline rpc_message_sent read_rpc_message_sent(const std::byte*& p, const std::byte* end) {
    rpc_message_sent out{};
    out.connection = detail::read_unaligned<std::uint64_t>(p, end);
    out.sequence = detail::read_unaligned<std::uint64_t>(p, end);
    out.task = detail::read_unaligned<std::uint64_t>(p, end);
    return out;
}

inline rpc_message_received read_rpc_message_received(const std::byte*& p, const std::byte* end) {
    rpc_message_received out{};
    out.connection = detail::read_unaligned<std::uint64_t>(p, end);
    out.sequence = detail::read_unaligned<std::uint64_t>(p, end);
    return out;
}

inline rpc_reply_sent read_rpc_reply_sent(const std::byte*& p, const std::byte* end) {
    rpc_reply_sent out{};
    out.connection = detail::read_unaligned<std::uint64_t>(p, end);
    out.sequence = detail::read_unaligned<std::uint64_t>(p, end);
    out.msg_id = detail::read_unaligned<std::int64_t>(p, end);
    out.task = detail::read_unaligned<std::uint64_t>(p, end);
    return out;
}

inline rpc_reply_received read_rpc_reply_received(const std::byte*& p, const std::byte* end) {
    rpc_reply_received out{};
    out.connection = detail::read_unaligned<std::uint64_t>(p, end);
    out.sequence = detail::read_unaligned<std::uint64_t>(p, end);
    out.msg_id = detail::read_unaligned<std::int64_t>(p, end);
    return out;
}

inline rpc_connections_snapshot_begin read_rpc_connections_snapshot_begin([[maybe_unused]] const std::byte*& p, [[maybe_unused]] const std::byte* end) {
    rpc_connections_snapshot_begin out{};
    return out;
}

inline rpc_connection_snapshot_entry read_rpc_connection_snapshot_entry(const std::byte*& p, const std::byte* end) {
    rpc_connection_snapshot_entry out{};
    out.connection = detail::read_unaligned<std::uint64_t>(p, end);
    out.local = detail::read_str(p, end);
    out.remote = detail::read_str(p, end);
    return out;
}

inline rpc_connections_snapshot_end read_rpc_connections_snapshot_end([[maybe_unused]] const std::byte*& p, [[maybe_unused]] const std::byte* end) {
    rpc_connections_snapshot_end out{};
    return out;
}

inline rpc_request_handled read_rpc_request_handled(const std::byte*& p, const std::byte* end) {
    rpc_request_handled out{};
    out.connection = detail::read_unaligned<std::uint64_t>(p, end);
    out.sequence = detail::read_unaligned<std::uint64_t>(p, end);
    out.prev = detail::read_unaligned<std::uint64_t>(p, end);
    out.task = detail::read_unaligned<std::uint64_t>(p, end);
    return out;
}

inline trace_objects_loaded read_trace_objects_loaded(const std::byte*& p, const std::byte* end) {
    trace_objects_loaded out{};
    out.count = detail::read_unaligned<std::uint32_t>(p, end);
    return out;
}

inline trace_object_unloaded read_trace_object_unloaded(const std::byte*& p, const std::byte* end) {
    trace_object_unloaded out{};
    out.build_id = detail::read_str(p, end);
    out.base_address = detail::read_unaligned<std::uint64_t>(p, end);
    return out;
}

inline trace_object_loaded read_trace_object_loaded(const std::byte*& p, const std::byte* end) {
    trace_object_loaded out{};
    out.build_id = detail::read_str(p, end);
    out.table_address = detail::read_unaligned<std::uint64_t>(p, end);
    out.base_address = detail::read_unaligned<std::uint64_t>(p, end);
    out.mapping_size = detail::read_unaligned<std::uint64_t>(p, end);
    return out;
}

inline stacktrace_sample read_stacktrace_sample(const std::byte*& p, const std::byte* end) {
    stacktrace_sample out{};
    out.shard = detail::read_unaligned<std::uint32_t>(p, end);
    out.time_ns = detail::read_unaligned<std::uint64_t>(p, end);
    out.frames = detail::read_bytes(p, end);
    return out;
}

inline constexpr tracepoint_metadata metadata_0{"clock_sync", "/home/michal/projects/cpp_template/modules/tracer/include/tracer/tracer.h", 1127, "void tracer::trace_buffers::write_clock_sync(event_level)", 0};
inline constexpr tracepoint_metadata metadata_1{"run_task", "seastar/src/core/scylla_tracer.cc", 115, "void seastar::trace_run_task(uint64_t, uint64_t, srcloc::location)", 0};
inline constexpr tracepoint_metadata metadata_2{"execution_stage", "seastar/src/core/scylla_tracer.cc", 120, "void seastar::trace_execution_stage(uint64_t, uint64_t)", 0};
inline constexpr tracepoint_metadata metadata_3{"cql_request", "seastar/src/core/scylla_tracer.cc", 125, "void seastar::trace_cql_request(uint64_t, uint64_t)", 0};
inline constexpr tracepoint_metadata metadata_4{"semaphore_execute", "seastar/src/core/scylla_tracer.cc", 130, "void seastar::trace_semaphore_execute(uint64_t, uint64_t)", 0};
inline constexpr tracepoint_metadata metadata_5{"io_begin", "seastar/src/core/scylla_tracer.cc", 135, "void seastar::trace_io_begin(uint64_t, uint64_t)", 0};
inline constexpr tracepoint_metadata metadata_6{"io_end", "seastar/src/core/scylla_tracer.cc", 140, "void seastar::trace_io_end(uint64_t, uint64_t)", 0};
inline constexpr tracepoint_metadata metadata_7{"prepared_statement_added", "seastar/src/core/scylla_tracer.cc", 147, "void seastar::trace_prepared_statement_added(std::string_view, std::string_view, std::span<const std::byte>)", 0};
inline constexpr tracepoint_metadata metadata_8{"prepared_statement_removed", "seastar/src/core/scylla_tracer.cc", 154, "void seastar::trace_prepared_statement_removed(std::string_view, std::string_view, std::span<const std::byte>)", 0};
inline constexpr tracepoint_metadata metadata_9{"prepared_query_run", "seastar/src/core/scylla_tracer.cc", 159, "void seastar::trace_prepared_query_run(std::span<const std::byte>)", 0};
inline constexpr tracepoint_metadata metadata_10{"prepared_statements_snapshot_begin", "seastar/src/core/scylla_tracer.cc", 164, "void seastar::trace_prepared_statements_snapshot_begin()", 0};
inline constexpr tracepoint_metadata metadata_11{"prepared_statement_snapshot_entry", "seastar/src/core/scylla_tracer.cc", 171, "void seastar::trace_prepared_statement_snapshot_entry(std::string_view, std::string_view, std::span<const std::byte>)", 0};
inline constexpr tracepoint_metadata metadata_12{"prepared_statements_snapshot_end", "seastar/src/core/scylla_tracer.cc", 176, "void seastar::trace_prepared_statements_snapshot_end()", 0};
inline constexpr tracepoint_metadata metadata_13{"rpc_connection_open", "seastar/src/core/scylla_tracer.cc", 190, "void seastar::trace_rpc_connection_open(uint64_t, std::string_view, std::string_view)", 0};
inline constexpr tracepoint_metadata metadata_14{"rpc_connection_close", "seastar/src/core/scylla_tracer.cc", 201, "void seastar::trace_rpc_connection_close(uint64_t)", 0};
inline constexpr tracepoint_metadata metadata_15{"rpc_message_sent", "seastar/src/core/scylla_tracer.cc", 209, "void seastar::trace_rpc_message_sent(uint64_t, uint64_t, uint64_t)", 0};
inline constexpr tracepoint_metadata metadata_16{"rpc_message_received", "seastar/src/core/scylla_tracer.cc", 215, "void seastar::trace_rpc_message_received(uint64_t, uint64_t)", 0};
inline constexpr tracepoint_metadata metadata_17{"rpc_reply_sent", "seastar/src/core/scylla_tracer.cc", 222, "void seastar::trace_rpc_reply_sent(uint64_t, uint64_t, int64_t, uint64_t)", 0};
inline constexpr tracepoint_metadata metadata_18{"rpc_reply_received", "seastar/src/core/scylla_tracer.cc", 228, "void seastar::trace_rpc_reply_received(uint64_t, uint64_t, int64_t)", 0};
inline constexpr tracepoint_metadata metadata_19{"rpc_connections_snapshot_begin", "seastar/src/core/scylla_tracer.cc", 235, "void seastar::trace_rpc_connections_snapshot()", 0};
inline constexpr tracepoint_metadata metadata_20{"rpc_connection_snapshot_entry", "seastar/src/core/scylla_tracer.cc", 237, "void seastar::trace_rpc_connections_snapshot()", 0};
inline constexpr tracepoint_metadata metadata_21{"rpc_connections_snapshot_end", "seastar/src/core/scylla_tracer.cc", 241, "void seastar::trace_rpc_connections_snapshot()", 0};
inline constexpr tracepoint_metadata metadata_22{"rpc_request_handled", "seastar/src/core/scylla_tracer.cc", 249, "void seastar::trace_rpc_request_handled(uint64_t, uint64_t, uint64_t, uint64_t)", 0};
inline constexpr tracepoint_metadata metadata_23{"trace_objects_loaded", "/home/michal/projects/cpp_template/modules/tracer/include/tracer/tracer.h", 1153, "void tracer::trace_buffers::note_objects_changed()", 0};
inline constexpr tracepoint_metadata metadata_24{"trace_object_unloaded", "/home/michal/projects/cpp_template/modules/tracer/include/tracer/tracer.h", 1168, "void tracer::trace_buffers::note_objects_changed()", 0};
inline constexpr tracepoint_metadata metadata_25{"trace_object_loaded", "/home/michal/projects/cpp_template/modules/tracer/include/tracer/tracer.h", 1181, "void tracer::trace_buffers::note_objects_changed()", 0};
inline constexpr tracepoint_metadata metadata_26{"stacktrace_sample", "seastar/src/core/scylla_stacktrace_sampler.cc", 82, "void seastar::(anonymous namespace)::trace_stacktrace_sample(std::uint32_t, std::uint64_t, std::span<const std::byte>)", 0};

}  // namespace detail

// Where a record's address comes from. `first_id` is the id of the object's
// entry 0, so an address that is `n * entry_stride` past the object's table
// belongs to id `first_id + n`.
inline constexpr std::size_t entry_stride = 48;
inline constexpr std::uint32_t trace_magic = 0x32435254;
inline constexpr std::size_t record_header_size = 16;
inline constexpr std::uint8_t metadata_level = 2;

struct object_descriptor {
    std::string_view build_id;
    std::uint32_t first_id;
    std::uint32_t count;
};

inline constexpr object_descriptor objects[] = {
    {"01d79ed24f712196f0d6a5c60048fe179c10e682", 0, 26},
    {"031d8c981cc111d747835b88605ef2a7cd183841", 26, 0},
    {"14ab4e5d89a6726d00357ff52f5430030e0741f8", 26, 0},
    {"2336665dcde4b83ab92e76e2de9df087e4d9d52f", 26, 0},
    {"2f3772c31f8ae1e34f4f8fcfee055663f8be2152", 26, 0},
    {"341e289fdd8a934c5ec6359ac67bc10efd15b21e", 26, 0},
    {"37d40ae813bd56440d2e4b796177d94b70e6f5b1", 26, 0},
    {"3890fe5da8e54c0ebce0c03d20e72836424d8f94", 26, 0},
    {"48f14782322a959c65ae96b2ce9d6b5919180831", 26, 0},
    {"7b4d84838262e842fbf03a46d3e3d60135b8a20a", 26, 0},
    {"812dbcc86f2a2d6a6ec964d488cc071e17d0bcf6", 26, 0},
    {"b4ccadde6bdd8a27427bde094488cb299d811bae", 26, 0},
    {"ce14072b4bac73de75d9bdc6f3327320e6b9db65", 26, 0},
    {"d6d480ae454bd1d2a366c447666e5817eb998437", 26, 0},
    {"dbd07c0d6e88ee4d1655fab639b711a1cd07d8ff", 26, 0},
    {"dd2ef14422fd9a8bf53ec27d8abba234e8fae440", 26, 0},
    {"eab16d42136776e092b375ec994661ecf3de14b9", 26, 0},
    {"f1a1ae2bd27498f870ff37e4819ef13634ca8954", 26, 0},
};

namespace detail {

// One object, for as long as it is mapped. `object` is null for a build ID this
// decoder was not generated from: the mapping is still kept, because it is what
// stops that object's records being attributed to the object below it -- they
// are refused by name instead.
struct mapping {
    std::uint64_t table;  // where the object's tracepoint table was mapped
    std::uint64_t base;   // and where the object itself begins
    std::uint64_t size;   // how far past the base it reaches
    const object_descriptor* object;
    std::string_view build_id;
};

// The mappings a record is read against, and the objects a location is read out
// of. One of these lives for the length of a decode; the mappings change as its
// metadata stream is consumed, which is what makes a record decode against the
// process as it was at the record's own timestamp.
class locator {
public:
    explicit locator(dso_directory& dsos) : dsos_(&dsos) {}

    std::vector<mapping> mappings;  // sorted by table address

    // Fill in a location from the object it points into. Silent about failure
    // by design: a location whose object is not in the directory, or which was
    // recorded before that object was mapped, stays unresolved and keeps the
    // address it came with. That is a decoder missing a file, not a corrupt
    // trace, and it should not stop the other records being read.
    void resolve(source_location& out) const {
        if (out.address == 0) {
            return;  // srcloc::location::none()
        }
        for (const mapping& m : mappings) {
            if (out.address < m.base || out.address - m.base >= m.size) {
                continue;
            }
            out.object = std::string(m.build_id);

            const std::span<const std::byte> image = dsos_->object(out.object);
            if (image.empty()) {
                return;  // the object is named, and not in the directory
            }
            // The four fields of a std::source_location, laid out as
            // srcloc::entry describes: two pointers then two 32-bit words. The
            // pointers hold link-time virtual addresses, and are read the same
            // way the entry itself was -- once the relocation that fills them in
            // has been applied, which in a shared object is where they live.
            const std::uint64_t entry_at = out.address - m.base;
            const std::byte* const entry = at_vaddr(image, entry_at, 24);
            if (entry == nullptr) {
                return;
            }
            std::uint64_t file_at = 0;
            std::uint64_t function_at = 0;
            std::memcpy(&file_at, entry, sizeof(file_at));
            std::memcpy(&function_at, entry + 8, sizeof(function_at));
            // In a shared object those two are zero in the file and the value is
            // in .rela.dyn; in a non-PIE executable they are already right.
            if (file_at == 0 || function_at == 0) {
                const auto& fixups = dsos_->relocations(out.object);
                file_at = relocated(fixups, entry_at, file_at);
                function_at = relocated(fixups, entry_at + 8, function_at);
            }
            std::memcpy(&out.line, entry + 16, sizeof(out.line));
            std::memcpy(&out.column, entry + 20, sizeof(out.column));
            out.file = string_at_vaddr(image, file_at);
            out.function = string_at_vaddr(image, function_at);
            out.resolved = !out.file.empty();
            return;
        }
    }

private:
    dso_directory* dsos_;
};

inline void resolve_run_task(run_task& out, const locator& where) {
    where.resolve(out.at);
}

}  // namespace detail

// The widest "file:line" in the trace, for a caller lining up a column of
// them.
inline constexpr std::size_t fileline_width = 78;

// Decode every record in `trace`, in timestamp order, calling cb(event, metadata)
// for each.
//
// `trace` is a whole trace: the magic, then a chunk per level. `cb` is expected
// to have an operator() per tracepoint struct it cares about -- plus, usually, a
// template one for the rest. A struct's string and byte fields point into
// `trace`, so they outlive the call only as long as it does.
//
// The metadata level is not delivered. Its events are how this function knows
// which object an address belongs to at the moment a record was written, so it
// consumes them: they are the frame the rest of the trace is read in rather
// than events of the program's own.
//
// `dsos` is where the objects a source location points into are found, by build
// ID. It is only consulted by a trace that carries a location, and a location it
// cannot place comes out unresolved rather than stopping the decode -- see
// "resolving a source location" above. The default reads $TRACE_DSO_DIR.
//
// Throws std::runtime_error on anything that cannot be decoded. A record is not
// self-delimiting, so a truncated or corrupt stream cannot be resynchronised
// past: the first bad byte ends the decode.
template <typename Callback>
void decode(std::span<const std::byte> trace, Callback&& cb,
            dso_directory& dsos = shared_dso_directory()) {
    const std::byte* p = trace.data();
    const std::byte* const end = p + trace.size();

    if (const auto magic = detail::read_unaligned<std::uint32_t>(p, end); magic != trace_magic) {
        throw std::runtime_error(std::format("not a trace: magic {:#x}", magic));
    }

    // One level's records. The metadata stream is put first because the merge
    // below breaks ties towards the earlier stream: a load event stamped with
    // the same timestamp as the first record from the object it loads has to be
    // read before it, not after.
    struct stream {
        const std::byte* p;
        const std::byte* end;
    };
    std::vector<stream> streams;
    bool have_metadata = false;
    while (p < end) {
        const auto level = detail::read_unaligned<std::uint8_t>(p, end);
        const auto length = detail::read_unaligned<std::uint64_t>(p, end);
        detail::require(p, end, length);
        if (level == metadata_level) {
            if (have_metadata) {
                throw std::runtime_error("a trace has one metadata stream; this one has two");
            }
            have_metadata = true;
            streams.insert(streams.begin(), {p, p + length});
        } else {
            streams.push_back({p, p + length});
        }
        p += length;
    }
    if (!have_metadata) {
        throw std::runtime_error(
            "a trace with no metadata stream: nothing in it says where its objects were mapped");
    }

    // What a record is read against: the objects mapped as of the record being
    // read, kept up to date by the load and unload events below.
    detail::locator where(dsos);
    std::vector<detail::mapping>& mappings = where.mappings;

    const auto load = [&mappings](const trace_object_loaded& event) {
        const object_descriptor* found = nullptr;
        for (const object_descriptor& object : objects) {
            if (object.build_id == event.build_id) {
                found = &object;
            }
        }
        mappings.push_back({event.table_address, event.base_address, event.mapping_size, found,
                            event.build_id});
        // Sorted so that "the object a tracepoint address is in" is a binary
        // search for the greatest table address not above it.
        std::sort(mappings.begin(), mappings.end(),
                  [](const detail::mapping& a, const detail::mapping& b) {
                      return a.table < b.table;
                  });
    };

    // By base address, which is the one thing that is unique per load: two
    // objects may have no tracepoint table between them, and a table is one
    // section inside an object rather than the object itself.
    const auto unload = [&mappings](const trace_object_unloaded& event) {
        for (auto it = mappings.begin(); it != mappings.end(); ++it) {
            if (it->base == event.base_address) {
                mappings.erase(it);
                return;
            }
        }
        throw std::runtime_error(
            std::format("object {} was unloaded without having been loaded", event.build_id));
    };

    // The prologue: a count, and that many load events. Read by that invariant
    // rather than by their addresses, because until they have been read there
    // is no object for an address to be in. See "the metadata stream" in
    // tracer.h.
    {
        stream& meta = streams.front();
        detail::read_unaligned<std::uint64_t>(meta.p, meta.end);  // entry address, not yet placeable
        detail::read_unaligned<std::uint64_t>(meta.p, meta.end);  // timestamp: zero, by construction
        const trace_objects_loaded counted = detail::read_trace_objects_loaded(meta.p, meta.end);
        for (std::uint32_t i = 0; i < counted.count; i++) {
            detail::read_unaligned<std::uint64_t>(meta.p, meta.end);
            detail::read_unaligned<std::uint64_t>(meta.p, meta.end);
            load(detail::read_trace_object_loaded(meta.p, meta.end));
        }
    }

    while (true) {
        // The earliest record still unread, over every stream. A record's
        // address and timestamp are fixed-width and come first, so how long it
        // is may be unknown but when it happened is not.
        stream* next = nullptr;
        std::uint64_t earliest = 0;
        for (stream& candidate : streams) {
            if (candidate.p == candidate.end) {
                continue;
            }
            detail::require(candidate.p, candidate.end, record_header_size);
            std::uint64_t at = 0;
            std::memcpy(&at, candidate.p + sizeof(std::uint64_t), sizeof(at));
            if (next == nullptr || at < earliest) {
                next = &candidate;
                earliest = at;
            }
        }
        if (next == nullptr) {
            break;
        }

        const std::byte*& q = next->p;
        const std::byte* const q_end = next->end;
        const auto address = detail::read_unaligned<std::uint64_t>(q, q_end);
        const auto timestamp = detail::read_unaligned<std::uint64_t>(q, q_end);

        const auto above = std::upper_bound(
            mappings.begin(), mappings.end(), address,
            [](std::uint64_t value, const detail::mapping& m) { return value < m.table; });
        if (above == mappings.begin()) {
            throw std::runtime_error(std::format(
                "tracepoint address {:#x} is below every object loaded at {}", address, timestamp));
        }
        const detail::mapping& from = *(above - 1);
        if (from.object == nullptr) {
            throw std::runtime_error(std::format(
                "tracepoint address {:#x} belongs to object {}, which this decoder was not "
                "generated from",
                address, from.build_id));
        }
        const std::uint64_t offset = address - from.table;
        if (offset % entry_stride != 0 || offset / entry_stride >= from.object->count) {
            throw std::runtime_error(std::format(
                "tracepoint address {:#x} is not an entry of object {}, which is what was at "
                "{:#x} at {}",
                address, from.build_id, from.table, timestamp));
        }
        const std::uint32_t id =
            from.object->first_id + static_cast<std::uint32_t>(offset / entry_stride);

        switch (id) {
            case 0: {
                tracepoint_metadata meta = detail::metadata_0;
                meta.timestamp = timestamp;
                clock_sync event = detail::read_clock_sync(q, q_end);
                cb(event, meta);
                break;
            }
            case 1: {
                tracepoint_metadata meta = detail::metadata_1;
                meta.timestamp = timestamp;
                run_task event = detail::read_run_task(q, q_end);
                detail::resolve_run_task(event, where);
                cb(event, meta);
                break;
            }
            case 2: {
                tracepoint_metadata meta = detail::metadata_2;
                meta.timestamp = timestamp;
                execution_stage event = detail::read_execution_stage(q, q_end);
                cb(event, meta);
                break;
            }
            case 3: {
                tracepoint_metadata meta = detail::metadata_3;
                meta.timestamp = timestamp;
                cql_request event = detail::read_cql_request(q, q_end);
                cb(event, meta);
                break;
            }
            case 4: {
                tracepoint_metadata meta = detail::metadata_4;
                meta.timestamp = timestamp;
                semaphore_execute event = detail::read_semaphore_execute(q, q_end);
                cb(event, meta);
                break;
            }
            case 5: {
                tracepoint_metadata meta = detail::metadata_5;
                meta.timestamp = timestamp;
                io_begin event = detail::read_io_begin(q, q_end);
                cb(event, meta);
                break;
            }
            case 6: {
                tracepoint_metadata meta = detail::metadata_6;
                meta.timestamp = timestamp;
                io_end event = detail::read_io_end(q, q_end);
                cb(event, meta);
                break;
            }
            case 7: {
                tracepoint_metadata meta = detail::metadata_7;
                meta.timestamp = timestamp;
                prepared_statement_added event = detail::read_prepared_statement_added(q, q_end);
                cb(event, meta);
                break;
            }
            case 8: {
                tracepoint_metadata meta = detail::metadata_8;
                meta.timestamp = timestamp;
                prepared_statement_removed event = detail::read_prepared_statement_removed(q, q_end);
                cb(event, meta);
                break;
            }
            case 9: {
                tracepoint_metadata meta = detail::metadata_9;
                meta.timestamp = timestamp;
                prepared_query_run event = detail::read_prepared_query_run(q, q_end);
                cb(event, meta);
                break;
            }
            case 10: {
                tracepoint_metadata meta = detail::metadata_10;
                meta.timestamp = timestamp;
                prepared_statements_snapshot_begin event = detail::read_prepared_statements_snapshot_begin(q, q_end);
                cb(event, meta);
                break;
            }
            case 11: {
                tracepoint_metadata meta = detail::metadata_11;
                meta.timestamp = timestamp;
                prepared_statement_snapshot_entry event = detail::read_prepared_statement_snapshot_entry(q, q_end);
                cb(event, meta);
                break;
            }
            case 12: {
                tracepoint_metadata meta = detail::metadata_12;
                meta.timestamp = timestamp;
                prepared_statements_snapshot_end event = detail::read_prepared_statements_snapshot_end(q, q_end);
                cb(event, meta);
                break;
            }
            case 13: {
                tracepoint_metadata meta = detail::metadata_13;
                meta.timestamp = timestamp;
                rpc_connection_open event = detail::read_rpc_connection_open(q, q_end);
                cb(event, meta);
                break;
            }
            case 14: {
                tracepoint_metadata meta = detail::metadata_14;
                meta.timestamp = timestamp;
                rpc_connection_close event = detail::read_rpc_connection_close(q, q_end);
                cb(event, meta);
                break;
            }
            case 15: {
                tracepoint_metadata meta = detail::metadata_15;
                meta.timestamp = timestamp;
                rpc_message_sent event = detail::read_rpc_message_sent(q, q_end);
                cb(event, meta);
                break;
            }
            case 16: {
                tracepoint_metadata meta = detail::metadata_16;
                meta.timestamp = timestamp;
                rpc_message_received event = detail::read_rpc_message_received(q, q_end);
                cb(event, meta);
                break;
            }
            case 17: {
                tracepoint_metadata meta = detail::metadata_17;
                meta.timestamp = timestamp;
                rpc_reply_sent event = detail::read_rpc_reply_sent(q, q_end);
                cb(event, meta);
                break;
            }
            case 18: {
                tracepoint_metadata meta = detail::metadata_18;
                meta.timestamp = timestamp;
                rpc_reply_received event = detail::read_rpc_reply_received(q, q_end);
                cb(event, meta);
                break;
            }
            case 19: {
                tracepoint_metadata meta = detail::metadata_19;
                meta.timestamp = timestamp;
                rpc_connections_snapshot_begin event = detail::read_rpc_connections_snapshot_begin(q, q_end);
                cb(event, meta);
                break;
            }
            case 20: {
                tracepoint_metadata meta = detail::metadata_20;
                meta.timestamp = timestamp;
                rpc_connection_snapshot_entry event = detail::read_rpc_connection_snapshot_entry(q, q_end);
                cb(event, meta);
                break;
            }
            case 21: {
                tracepoint_metadata meta = detail::metadata_21;
                meta.timestamp = timestamp;
                rpc_connections_snapshot_end event = detail::read_rpc_connections_snapshot_end(q, q_end);
                cb(event, meta);
                break;
            }
            case 22: {
                tracepoint_metadata meta = detail::metadata_22;
                meta.timestamp = timestamp;
                rpc_request_handled event = detail::read_rpc_request_handled(q, q_end);
                cb(event, meta);
                break;
            }
            case 23:
                throw std::runtime_error(
                    "a trace_objects_loaded event past the start of the metadata stream");
            case 24:
                unload(detail::read_trace_object_unloaded(q, q_end));
                break;
            case 25:
                load(detail::read_trace_object_loaded(q, q_end));
                break;
            case 26: {
                tracepoint_metadata meta = detail::metadata_26;
                meta.timestamp = timestamp;
                stacktrace_sample event = detail::read_stacktrace_sample(q, q_end);
                cb(event, meta);
                break;
            }
            default:
                throw std::runtime_error(std::format("bad tracepoint id {}", id));
        }
    }
}

}  // namespace trace

// Reopened: decode() above closed it, and this is a second, independent way in
// -- nothing here is needed to read a record.
namespace trace {

// One object, as the metadata prologue described it: the build ID that names
// it and the span of addresses it was mapped over.
//
// decode() keeps this to itself, because a *record* is read against the objects
// as they were at its own timestamp. This is for the other kind of address: a
// stack frame, or anything else a tracepoint carries as a bare pointer into
// the process. Those have no reader of their own -- what is at an address is in
// the object, not in the trace -- so a caller is handed the mappings and does
// its own resolving, with llvm-addr2line or anything else that takes a file and
// an offset.
struct object_mapping {
    std::string build_id;
    std::uint64_t base;  // where the object was mapped
    std::uint64_t size;  // how far past the base it reached
};

// The objects the prologue of `trace`'s metadata stream listed, which is every
// object the thread had mapped when its rings were built. A library dlopened
// afterwards is in the metadata stream proper rather than the prologue and does
// not appear here; nothing that traces today does that.
inline std::vector<object_mapping> trace_mappings(std::span<const std::byte> trace) {
    const std::byte* p = trace.data();
    const std::byte* const end = p + trace.size();
    if (detail::read_unaligned<std::uint32_t>(p, end) != trace_magic) {
        throw std::runtime_error("not a trace");
    }
    while (p < end) {
        const auto level = detail::read_unaligned<std::uint8_t>(p, end);
        const auto length = detail::read_unaligned<std::uint64_t>(p, end);
        detail::require(p, end, length);
        if (level != metadata_level) {
            p += length;
            continue;
        }
        const std::byte* q = p;
        const std::byte* const q_end = p + length;
        detail::read_unaligned<std::uint64_t>(q, q_end);  // entry address
        detail::read_unaligned<std::uint64_t>(q, q_end);  // timestamp
        const trace_objects_loaded counted = detail::read_trace_objects_loaded(q, q_end);
        std::vector<object_mapping> out;
        out.reserve(counted.count);
        for (std::uint32_t i = 0; i < counted.count; i++) {
            detail::read_unaligned<std::uint64_t>(q, q_end);
            detail::read_unaligned<std::uint64_t>(q, q_end);
            const trace_object_loaded loaded = detail::read_trace_object_loaded(q, q_end);
            out.push_back({std::string(loaded.build_id), loaded.base_address,
                           loaded.mapping_size});
        }
        return out;
    }
    throw std::runtime_error("a trace with no metadata stream");
}

// The object an address is in, or null. Linear, over a list of a few dozen: the
// mappings are not sorted, and a caller resolving a stack does this once per
// frame and then caches the answer.
[[nodiscard]] inline const object_mapping* mapping_of(
        const std::vector<object_mapping>& mappings, std::uint64_t address) {
    for (const object_mapping& m : mappings) {
        if (address >= m.base && address - m.base < m.size) {
            return &m;
        }
    }
    return nullptr;
}

}  // namespace trace
