// Generated by tracer::generate_decoder_source(). Do not edit.
//
// One struct per tracepoint of the objects this was generated from, and a
// decode() that turns a trace of those objects into those structs.
#pragma once

#include <algorithm>
#include <cstddef>
#include <cstdint>
#include <cstring>
#include <format>
#include <span>
#include <stdexcept>
#include <string>
#include <string_view>
#include <type_traits>
#include <vector>

namespace trace {

// Which tracepoint a record came from, and when it was taken. Everything but
// the timestamp is a fact about the call site, fixed at compile time.
struct tracepoint_metadata {
    std::string_view name;
    std::string_view file;
    int line;
    std::string_view function;
    std::uint64_t timestamp;
};

namespace detail {

// Every read is bounded by the end of the trace. A record is not
// self-delimiting, so a truncated one cannot be recognised as short until a
// field runs off the end -- and a field that ran off the end must be an
// exception rather than a view into whatever follows the buffer.
inline void require(const std::byte* p, const std::byte* end, std::size_t n) {
    if (static_cast<std::size_t>(end - p) < n) {
        throw std::runtime_error(
            std::format("truncated trace: {} bytes left, {} wanted", end - p, n));
    }
}

template <typename To>
    requires std::is_trivially_copyable_v<To>
To read_unaligned(const std::byte*& p, const std::byte* end) {
    require(p, end, sizeof(To));
    To dst;
    std::memcpy(&dst, p, sizeof(To));
    p += sizeof(To);
    return dst;
}

// Length-prefixed runs. Both views point into the trace buffer rather than
// copying out of it, which is what keeps decoding allocation-free -- and what
// makes them valid only as long as that buffer is.
inline std::span<const std::byte> read_bytes(const std::byte*& p, const std::byte* end) {
    const auto len = read_unaligned<std::uint16_t>(p, end);
    require(p, end, len);
    const std::span<const std::byte> out(p, len);
    p += len;
    return out;
}

inline std::string_view read_str(const std::byte*& p, const std::byte* end) {
    const std::span<const std::byte> raw = read_bytes(p, end);
    return {reinterpret_cast<const char*>(raw.data()), raw.size()};
}

// How to_string() renders one field. Free functions rather than a formatter
// specialisation, so that a caller printing a field itself can reach for the
// same rendering without adopting it for every std::span in its program.
inline std::string field_to_string(std::span<const std::byte> v) {
    std::string out;
    for (std::byte b : v) {
        out += std::format("{:02x}", std::to_integer<unsigned>(b));
    }
    return out;
}

inline std::string field_to_string(std::string_view v) { return std::string(v); }

inline std::string field_to_string(const void* v) { return std::format("{}", v); }

template <typename T>
std::string field_to_string(const T& v) {
    return std::format("{}", v);
}

}  // namespace detail

// seastar/src/core/scylla_tracer.cc:80
struct run_task {
    std::uint64_t prev;
    std::uint64_t task;

    [[nodiscard]] std::string to_string() const {
        return std::format("run_task{{prev={}, task={}}}",
                           detail::field_to_string(prev),
                           detail::field_to_string(task));
    }
};

// seastar/src/core/scylla_tracer.cc:85
struct execution_stage {
    std::uint64_t prev;
    std::uint64_t task;

    [[nodiscard]] std::string to_string() const {
        return std::format("execution_stage{{prev={}, task={}}}",
                           detail::field_to_string(prev),
                           detail::field_to_string(task));
    }
};

// seastar/src/core/scylla_tracer.cc:90
struct cql_request {
    std::uint64_t prev;
    std::uint64_t task;

    [[nodiscard]] std::string to_string() const {
        return std::format("cql_request{{prev={}, task={}}}",
                           detail::field_to_string(prev),
                           detail::field_to_string(task));
    }
};

// seastar/src/core/scylla_tracer.cc:95
struct semaphore_execute {
    std::uint64_t prev;
    std::uint64_t task;

    [[nodiscard]] std::string to_string() const {
        return std::format("semaphore_execute{{prev={}, task={}}}",
                           detail::field_to_string(prev),
                           detail::field_to_string(task));
    }
};

// seastar/src/core/scylla_tracer.cc:100
struct io_begin {
    std::uint64_t task;
    std::uint64_t io;

    [[nodiscard]] std::string to_string() const {
        return std::format("io_begin{{task={}, io={}}}",
                           detail::field_to_string(task),
                           detail::field_to_string(io));
    }
};

// seastar/src/core/scylla_tracer.cc:105
struct io_end {
    std::uint64_t task;
    std::uint64_t io;

    [[nodiscard]] std::string to_string() const {
        return std::format("io_end{{task={}, io={}}}",
                           detail::field_to_string(task),
                           detail::field_to_string(io));
    }
};

// /home/michal/projects/cpp_template/modules/tracer/include/tracer/tracer.h:915
struct trace_objects_loaded {
    std::uint32_t count;

    [[nodiscard]] std::string to_string() const {
        return std::format("trace_objects_loaded{{count={}}}",
                           detail::field_to_string(count));
    }
};

// /home/michal/projects/cpp_template/modules/tracer/include/tracer/tracer.h:930
struct trace_object_unloaded {
    std::string_view build_id;
    std::uint64_t table_address;

    [[nodiscard]] std::string to_string() const {
        return std::format("trace_object_unloaded{{build_id={}, table_address={}}}",
                           detail::field_to_string(build_id),
                           detail::field_to_string(table_address));
    }
};

// /home/michal/projects/cpp_template/modules/tracer/include/tracer/tracer.h:941
struct trace_object_loaded {
    std::string_view build_id;
    std::uint64_t table_address;

    [[nodiscard]] std::string to_string() const {
        return std::format("trace_object_loaded{{build_id={}, table_address={}}}",
                           detail::field_to_string(build_id),
                           detail::field_to_string(table_address));
    }
};

namespace detail {

inline run_task read_run_task(const std::byte*& p, const std::byte* end) {
    run_task out{};
    out.prev = detail::read_unaligned<std::uint64_t>(p, end);
    out.task = detail::read_unaligned<std::uint64_t>(p, end);
    return out;
}

inline execution_stage read_execution_stage(const std::byte*& p, const std::byte* end) {
    execution_stage out{};
    out.prev = detail::read_unaligned<std::uint64_t>(p, end);
    out.task = detail::read_unaligned<std::uint64_t>(p, end);
    return out;
}

inline cql_request read_cql_request(const std::byte*& p, const std::byte* end) {
    cql_request out{};
    out.prev = detail::read_unaligned<std::uint64_t>(p, end);
    out.task = detail::read_unaligned<std::uint64_t>(p, end);
    return out;
}

inline semaphore_execute read_semaphore_execute(const std::byte*& p, const std::byte* end) {
    semaphore_execute out{};
    out.prev = detail::read_unaligned<std::uint64_t>(p, end);
    out.task = detail::read_unaligned<std::uint64_t>(p, end);
    return out;
}

inline io_begin read_io_begin(const std::byte*& p, const std::byte* end) {
    io_begin out{};
    out.task = detail::read_unaligned<std::uint64_t>(p, end);
    out.io = detail::read_unaligned<std::uint64_t>(p, end);
    return out;
}

inline io_end read_io_end(const std::byte*& p, const std::byte* end) {
    io_end out{};
    out.task = detail::read_unaligned<std::uint64_t>(p, end);
    out.io = detail::read_unaligned<std::uint64_t>(p, end);
    return out;
}

inline trace_objects_loaded read_trace_objects_loaded(const std::byte*& p, const std::byte* end) {
    trace_objects_loaded out{};
    out.count = detail::read_unaligned<std::uint32_t>(p, end);
    return out;
}

inline trace_object_unloaded read_trace_object_unloaded(const std::byte*& p, const std::byte* end) {
    trace_object_unloaded out{};
    out.build_id = detail::read_str(p, end);
    out.table_address = detail::read_unaligned<std::uint64_t>(p, end);
    return out;
}

inline trace_object_loaded read_trace_object_loaded(const std::byte*& p, const std::byte* end) {
    trace_object_loaded out{};
    out.build_id = detail::read_str(p, end);
    out.table_address = detail::read_unaligned<std::uint64_t>(p, end);
    return out;
}

inline constexpr tracepoint_metadata metadata_0{"run_task", "seastar/src/core/scylla_tracer.cc", 80, "void seastar::trace_run_task(uint64_t, uint64_t)", 0};
inline constexpr tracepoint_metadata metadata_1{"execution_stage", "seastar/src/core/scylla_tracer.cc", 85, "void seastar::trace_execution_stage(uint64_t, uint64_t)", 0};
inline constexpr tracepoint_metadata metadata_2{"cql_request", "seastar/src/core/scylla_tracer.cc", 90, "void seastar::trace_cql_request(uint64_t, uint64_t)", 0};
inline constexpr tracepoint_metadata metadata_3{"semaphore_execute", "seastar/src/core/scylla_tracer.cc", 95, "void seastar::trace_semaphore_execute(uint64_t, uint64_t)", 0};
inline constexpr tracepoint_metadata metadata_4{"io_begin", "seastar/src/core/scylla_tracer.cc", 100, "void seastar::trace_io_begin(uint64_t, uint64_t)", 0};
inline constexpr tracepoint_metadata metadata_5{"io_end", "seastar/src/core/scylla_tracer.cc", 105, "void seastar::trace_io_end(uint64_t, uint64_t)", 0};
inline constexpr tracepoint_metadata metadata_6{"trace_objects_loaded", "/home/michal/projects/cpp_template/modules/tracer/include/tracer/tracer.h", 915, "void tracer::trace_buffers::note_objects_changed()", 0};
inline constexpr tracepoint_metadata metadata_7{"trace_object_unloaded", "/home/michal/projects/cpp_template/modules/tracer/include/tracer/tracer.h", 930, "void tracer::trace_buffers::note_objects_changed()", 0};
inline constexpr tracepoint_metadata metadata_8{"trace_object_loaded", "/home/michal/projects/cpp_template/modules/tracer/include/tracer/tracer.h", 941, "void tracer::trace_buffers::note_objects_changed()", 0};

}  // namespace detail

// Where a record's address comes from. `first_id` is the id of the object's
// entry 0, so an address that is `n * entry_stride` past the object's table
// belongs to id `first_id + n`.
inline constexpr std::size_t entry_stride = 48;
inline constexpr std::uint32_t trace_magic = 0x32435254;
inline constexpr std::size_t record_header_size = 16;
inline constexpr std::uint8_t metadata_level = 2;

struct object_descriptor {
    std::string_view build_id;
    std::uint32_t first_id;
    std::uint32_t count;
};

inline constexpr object_descriptor objects[] = {
    {"ceb6f0921bfd31a87175ab0e10369e4252700240", 0, 9},
};

// The widest "file:line" in the trace, for a caller lining up a column of
// them.
inline constexpr std::size_t fileline_width = 77;

// Decode every record in `trace`, in timestamp order, calling cb(event, metadata)
// for each.
//
// `trace` is a whole trace: the magic, then a chunk per level. `cb` is expected
// to have an operator() per tracepoint struct it cares about -- plus, usually, a
// template one for the rest. A struct's string and byte fields point into
// `trace`, so they outlive the call only as long as it does.
//
// The metadata level is not delivered. Its events are how this function knows
// which object an address belongs to at the moment a record was written, so it
// consumes them: they are the frame the rest of the trace is read in rather
// than events of the program's own.
//
// Throws std::runtime_error on anything that cannot be decoded. A record is not
// self-delimiting, so a truncated or corrupt stream cannot be resynchronised
// past: the first bad byte ends the decode.
template <typename Callback>
void decode(std::span<const std::byte> trace, Callback&& cb) {
    const std::byte* p = trace.data();
    const std::byte* const end = p + trace.size();

    if (const auto magic = detail::read_unaligned<std::uint32_t>(p, end); magic != trace_magic) {
        throw std::runtime_error(std::format("not a trace: magic {:#x}", magic));
    }

    // One level's records. The metadata stream is put first because the merge
    // below breaks ties towards the earlier stream: a load event stamped with
    // the same timestamp as the first record from the object it loads has to be
    // read before it, not after.
    struct stream {
        const std::byte* p;
        const std::byte* end;
    };
    std::vector<stream> streams;
    bool have_metadata = false;
    while (p < end) {
        const auto level = detail::read_unaligned<std::uint8_t>(p, end);
        const auto length = detail::read_unaligned<std::uint64_t>(p, end);
        detail::require(p, end, length);
        if (level == metadata_level) {
            if (have_metadata) {
                throw std::runtime_error("a trace has one metadata stream; this one has two");
            }
            have_metadata = true;
            streams.insert(streams.begin(), {p, p + length});
        } else {
            streams.push_back({p, p + length});
        }
        p += length;
    }
    if (!have_metadata) {
        throw std::runtime_error(
            "a trace with no metadata stream: nothing in it says where its objects were mapped");
    }

    // Where an object is mapped, for as long as it is. `object` is null for a
    // build ID this decoder was not generated from: the mapping is still kept,
    // because it is what stops that object's records being attributed to the
    // object below it -- they are refused by name instead.
    struct mapping {
        std::uint64_t address;
        const object_descriptor* object;
        std::string_view build_id;
    };
    std::vector<mapping> mappings;

    const auto load = [&mappings](const trace_object_loaded& event) {
        const object_descriptor* found = nullptr;
        for (const object_descriptor& object : objects) {
            if (object.build_id == event.build_id) {
                found = &object;
            }
        }
        mappings.push_back({event.table_address, found, event.build_id});
        // Sorted so that "the object an address is in" is a binary search for
        // the greatest table address not above it.
        std::sort(mappings.begin(), mappings.end(),
                  [](const mapping& a, const mapping& b) { return a.address < b.address; });
    };

    const auto unload = [&mappings](const trace_object_unloaded& event) {
        for (auto it = mappings.begin(); it != mappings.end(); ++it) {
            if (it->address == event.table_address) {
                mappings.erase(it);
                return;
            }
        }
        throw std::runtime_error(
            std::format("object {} was unloaded without having been loaded", event.build_id));
    };

    // The prologue: a count, and that many load events. Read by that invariant
    // rather than by their addresses, because until they have been read there
    // is no object for an address to be in. See "the metadata stream" in
    // tracer.h.
    {
        stream& meta = streams.front();
        detail::read_unaligned<std::uint64_t>(meta.p, meta.end);  // entry address, not yet placeable
        detail::read_unaligned<std::uint64_t>(meta.p, meta.end);  // timestamp: zero, by construction
        const trace_objects_loaded counted = detail::read_trace_objects_loaded(meta.p, meta.end);
        for (std::uint32_t i = 0; i < counted.count; i++) {
            detail::read_unaligned<std::uint64_t>(meta.p, meta.end);
            detail::read_unaligned<std::uint64_t>(meta.p, meta.end);
            load(detail::read_trace_object_loaded(meta.p, meta.end));
        }
    }

    while (true) {
        // The earliest record still unread, over every stream. A record's
        // address and timestamp are fixed-width and come first, so how long it
        // is may be unknown but when it happened is not.
        stream* next = nullptr;
        std::uint64_t earliest = 0;
        for (stream& candidate : streams) {
            if (candidate.p == candidate.end) {
                continue;
            }
            detail::require(candidate.p, candidate.end, record_header_size);
            std::uint64_t at = 0;
            std::memcpy(&at, candidate.p + sizeof(std::uint64_t), sizeof(at));
            if (next == nullptr || at < earliest) {
                next = &candidate;
                earliest = at;
            }
        }
        if (next == nullptr) {
            break;
        }

        const std::byte*& q = next->p;
        const std::byte* const q_end = next->end;
        const auto address = detail::read_unaligned<std::uint64_t>(q, q_end);
        const auto timestamp = detail::read_unaligned<std::uint64_t>(q, q_end);

        const auto above = std::upper_bound(
            mappings.begin(), mappings.end(), address,
            [](std::uint64_t value, const mapping& m) { return value < m.address; });
        if (above == mappings.begin()) {
            throw std::runtime_error(std::format(
                "tracepoint address {:#x} is below every object loaded at {}", address, timestamp));
        }
        const mapping& from = *(above - 1);
        if (from.object == nullptr) {
            throw std::runtime_error(std::format(
                "tracepoint address {:#x} belongs to object {}, which this decoder was not "
                "generated from",
                address, from.build_id));
        }
        const std::uint64_t offset = address - from.address;
        if (offset % entry_stride != 0 || offset / entry_stride >= from.object->count) {
            throw std::runtime_error(std::format(
                "tracepoint address {:#x} is not an entry of object {}, which is what was at "
                "{:#x} at {}",
                address, from.build_id, from.address, timestamp));
        }
        const std::uint32_t id =
            from.object->first_id + static_cast<std::uint32_t>(offset / entry_stride);

        switch (id) {
            case 0: {
                tracepoint_metadata meta = detail::metadata_0;
                meta.timestamp = timestamp;
                cb(detail::read_run_task(q, q_end), meta);
                break;
            }
            case 1: {
                tracepoint_metadata meta = detail::metadata_1;
                meta.timestamp = timestamp;
                cb(detail::read_execution_stage(q, q_end), meta);
                break;
            }
            case 2: {
                tracepoint_metadata meta = detail::metadata_2;
                meta.timestamp = timestamp;
                cb(detail::read_cql_request(q, q_end), meta);
                break;
            }
            case 3: {
                tracepoint_metadata meta = detail::metadata_3;
                meta.timestamp = timestamp;
                cb(detail::read_semaphore_execute(q, q_end), meta);
                break;
            }
            case 4: {
                tracepoint_metadata meta = detail::metadata_4;
                meta.timestamp = timestamp;
                cb(detail::read_io_begin(q, q_end), meta);
                break;
            }
            case 5: {
                tracepoint_metadata meta = detail::metadata_5;
                meta.timestamp = timestamp;
                cb(detail::read_io_end(q, q_end), meta);
                break;
            }
            case 6:
                throw std::runtime_error(
                    "a trace_objects_loaded event past the start of the metadata stream");
            case 7:
                unload(detail::read_trace_object_unloaded(q, q_end));
                break;
            case 8:
                load(detail::read_trace_object_loaded(q, q_end));
                break;
            default:
                throw std::runtime_error(std::format("bad tracepoint id {}", id));
        }
    }
}

}  // namespace trace
