rust_library(
    name = "libafl-wrapper",
    srcs = ["src/lib.rs"],
    soname = "liblibafl_c.so",
    deps = [
        "libafl_third_party//:libafl",
        "libafl_third_party//:libafl_bolts",
        "libafl_third_party//:libafl_targets",
    ],
    visibility = ["PUBLIC"],
)
