load("//buck:module.bzl", "add_module")

add_module(
    name = "test_rng",
    srcs = [
        "test_rng.cc",
        "backend_demo_test.cc",
    ],
    exported_headers = {
        "test_rng/test_rng.h": "include/test_rng/test_rng.h",
    },
    deps = [
        "//modules/exhaustigen:exhaustigen",
        "//:hegel",
    ] + select({
        "//:libafl": ["//modules/libafl:libafl_c"],
        "DEFAULT": [],
    }),
    compiler_flags = select({
        "//:libafl": ["-DBUILD_LIBAFL"],
        "DEFAULT": [],
    }),
    exported_needs_coverage_instrumentation = select({
        "//:libafl": True,
        "DEFAULT": False,
    }),
    exported_linker_flags = select({
        "//:libafl": ["-fno-sanitize-link-runtime"],
        "DEFAULT": [],
    }),
    module_source_dir = "modules/test_rng",
)
