load("@root//buck:flake.bzl", "flake")
load("@root//buck:cxx.bzl", "nix_cxx_toolchain")
load("@root//buck:rust.bzl", "nix_rust_toolchain")
load("@root//buck:python.bzl", "nix_python_bootstrap_toolchain")
load("@prelude//tests:test_toolchain.bzl", "noop_test_toolchain")
load("@prelude//toolchains:genrule.bzl", "system_genrule_toolchain")
load(
    "@prelude//toolchains:remote_test_execution.bzl",
    "remote_test_execution_toolchain",
)

# use the `cxx` flake package output from `./nix` to provide the compiler tools
flake.package(
    name = "nix_cc",
    binaries = [
        "ar",
        "cc",
        "c++",
        "nm",
        "objcopy",
        "ranlib",
        "strip",
    ],
    package = "cxx",
    path = "root//:flake",
)

# provide the `cxx` toolchain using the `:nix_cc` target
nix_cxx_toolchain(
    name = "cxx",
    nix_cc = ":nix_cc",
    visibility = ["PUBLIC"],
)

flake.package(
    name = "python",
    binary = "python3",
    package = "python3",
    path = "root//:flake",
)

nix_python_bootstrap_toolchain(
    name = "python_bootstrap",
    python = ":python",
    visibility = ["PUBLIC"],
)

noop_test_toolchain(
    name = "test",
    visibility = ["PUBLIC"],
)

remote_test_execution_toolchain(
    name = "remote_test_execution",
    visibility = ["PUBLIC"],
)

system_genrule_toolchain(
    name = "genrule",
    visibility = ["PUBLIC"],
)

flake.package(
    name = "rustc",
    binary = "rustc",
    binaries = ["rustdoc"],
    path = "root//:flake",
)

flake.package(
    name = "clippy",
    binary = "clippy-driver",
    path = "root//:flake",
)

nix_rust_toolchain(
    name = "rust",
    clippy = ":clippy",
    default_edition = "2024",
    rustc = ":rustc",
    rustdoc = ":rustc[rustdoc]",
    visibility = ["PUBLIC"],
)
