load("@root//buck:flake.bzl", "flake")
load("@root//buck:cxx.bzl", "nix_cxx_toolchain")
load("@root//buck:python.bzl", "nix_python_bootstrap_toolchain")

# use the `cxx` flake package output from `./nix` to provide the compiler tools
flake.package(
    name = "nix_cc",
    binaries = [
        "ar",
        "cc",
        "c++",
        "nm",
        "objcopy",
        "ranlib",
        "strip",
    ],
    package = "cxx",
    path = "root//:flake",
)

# provide the `cxx` toolchain using the `:nix_cc` target
nix_cxx_toolchain(
    name = "cxx",
    nix_cc = ":nix_cc",
    visibility = ["PUBLIC"],
)

# drives `flake.prebuilt_cmake_library()`, which configures a CMake project to
# discover a package's include dirs and libraries
flake.package(
    name = "cmake",
    binary = "cmake",
    package = "cmake",
    path = "root//:flake",
    visibility = ["PUBLIC"],
)

flake.package(
    name = "python",
    binary = "python3",
    package = "python3",
    path = "root//:flake",
)

nix_python_bootstrap_toolchain(
    name = "python_bootstrap",
    python = ":python",
    visibility = ["PUBLIC"],
)