load("//buck:module.bzl", "add_module")

add_module(
    name = "pt",
    srcs = [
        "pt_control.cc",
        "pt_control_test.cc",
        "pt_trace.cc",
    ],
    exported_headers = {
        "pt/pt_control.h": "include/pt/pt_control.h",
        "pt/pt_trace.h": "include/pt/pt_trace.h",
    },
    deps = [
        "//:doctest",
    ],
    module_source_dir = "modules/pt",
)
