#include "tracer/codegen.h"

#include <format>
#include <sstream>
#include <string>
#include <string_view>
#include <vector>

#include "tracer/tracer.h"

namespace tracer {
namespace {

std::vector<std::string> split_signature(std::string_view signature) {
    std::vector<std::string> out;
    std::stringstream ss{std::string(signature)};
    std::string token;
    while (std::getline(ss, token, ',')) {
        if (!token.empty()) {
            out.push_back(token);
        }
    }
    return out;
}

// The C++ type a signature token decodes into. Unrecognised and oversized
// arguments were written as opaque fixed-width slots, so they come back as
// spans and are printed as hex.
std::string_view decoded_type(std::string_view sig) {
    if (sig == "u64") return "std::uint64_t";
    if (sig == "i64") return "std::int64_t";
    if (sig == "u32") return "std::uint32_t";
    if (sig == "i32") return "std::int32_t";
    if (sig == "u16") return "std::uint16_t";
    if (sig == "i16") return "std::int16_t";
    if (sig == "u8") return "std::uint8_t";
    if (sig == "i8") return "std::int8_t";
    if (sig == "bool") return "bool";
    if (sig == "ptr") return "const void*";
    return "std::span<const std::byte>";  // bytes, unknown64, unknown128
}

bool is_opaque(std::string_view sig) {
    return sig == "bytes" || sig == "unknown64" || sig == "unknown128";
}

std::string generate_prologue() {
    return R"cpp(// Generated by tracer::generate_decoder_source(). Do not edit.
#include <cstddef>
#include <cstdint>
#include <cstring>
#include <format>
#include <fstream>
#include <iostream>
#include <iterator>
#include <span>
#include <vector>

namespace {

template <typename To>
    requires std::is_trivially_copyable_v<To>
To read_unaligned(const std::byte*& p) {
    To dst;
    std::memcpy(&dst, p, sizeof(To));
    p += sizeof(To);
    return dst;
}

struct hex_bytes {
    std::span<const std::byte> v;
};

}  // namespace

template <>
struct std::formatter<hex_bytes> {
    static constexpr auto parse(std::format_parse_context& ctx) { return ctx.begin(); }

    static auto format(const hex_bytes& h, std::format_context& ctx) {
        auto out = ctx.out();
        for (std::byte b : h.v) {
            out = std::format_to(out, "{:02x}", std::to_integer<unsigned>(b));
        }
        return out;
    }
};

namespace {

)cpp";
}

std::string generate_deserializer(std::size_t id,
                                  const tracepoint_entry& entry,
                                  std::size_t fileline_width) {
    const std::vector<std::string> sigs = split_signature(entry.signature);

    std::string code;
    code += std::format("// {}:{}  [{}]\n", entry.file, entry.line, entry.signature);
    code += std::format("void deserialize_{}(const std::byte*& p) {{\n", id);
    code += "    const auto ts = read_unaligned<std::uint64_t>(p);\n";

    for (std::size_t i = 0; i < sigs.size(); ++i) {
        const std::string& sig = sigs[i];
        const std::size_t n = i + 1;
        if (sig == "bytes") {
            code += std::format("    const std::size_t len_{} = read_unaligned<std::uint16_t>(p);\n", n);
            code += std::format("    const std::span<const std::byte> arg_{}(p, len_{});\n", n, n);
            code += std::format("    p += len_{};\n", n);
        } else if (sig == "unknown64" || sig == "unknown128") {
            const int width = sig == "unknown64" ? 8 : 16;
            code += std::format("    const std::span<const std::byte> arg_{}(p, {});\n", n, width);
            code += std::format("    p += {};\n", width);
        } else if (sig == "ptr") {
            code += std::format(
                "    const void* const arg_{} = reinterpret_cast<const void*>(read_unaligned<std::uintptr_t>(p));\n",
                n);
        } else {
            code += std::format("    const {} arg_{} = read_unaligned<{}>(p);\n",
                                decoded_type(sig), n, decoded_type(sig));
        }
    }

    // The tracepoint's name is the format string. Placeholders that do not
    // match the decoded arguments fail to compile right here, which is the
    // reason for generating source instead of interpreting the table.
    code += std::format(
        "    std::cout << std::format(R\"---({{:>18}} | {{:<{}}} | {{:<5}} | {})---\"\n"
        "                             \"\\n\",\n"
        "                             ts, \"{}:{}\", \"{}\"",
        fileline_width, entry.name, entry.file, entry.line, to_string(static_cast<log_level>(entry.level)));

    for (std::size_t i = 0; i < sigs.size(); ++i) {
        code += is_opaque(sigs[i]) ? std::format(", hex_bytes{{arg_{}}}", i + 1)
                                   : std::format(", arg_{}", i + 1);
    }
    code += ");\n}\n\n";
    return code;
}

std::string generate_epilogue(std::size_t count) {
    std::string code = "using deserializer = void (*)(const std::byte*&);\n\n";
    code += "constexpr deserializer deserializers[] = {\n";
    for (std::size_t i = 0; i < count; ++i) {
        code += std::format("    deserialize_{},\n", i);
    }
    if (count == 0) {
        code += "    nullptr,  // no tracepoints in the producing binary\n";
    }
    code += "};\n\n";
    code += std::format("constexpr std::size_t tracepoint_count = {};\n", count);
    code += std::format("constexpr std::size_t record_header_size = {};\n\n", record_header_size);

    code += R"cpp(}  // namespace

int main(int argc, char** argv) {
    if (argc != 2) {
        std::cerr << "usage: " << argv[0] << " <trace-file>\n";
        return 2;
    }

    std::ifstream in(argv[1], std::ios::binary);
    if (!in) {
        std::cerr << "cannot open " << argv[1] << "\n";
        return 1;
    }
    const std::vector<char> raw{std::istreambuf_iterator<char>(in), std::istreambuf_iterator<char>()};

    const auto* p = reinterpret_cast<const std::byte*>(raw.data());
    const std::byte* const end = p + raw.size();

    while (p < end) {
        // A record is not self-delimiting, so a truncated or corrupt stream has
        // to stop the decode rather than be resynchronised past.
        if (static_cast<std::size_t>(end - p) < record_header_size) {
            std::cerr << "truncated trace: " << (end - p) << " trailing bytes\n";
            return 1;
        }
        const auto id = read_unaligned<std::uint32_t>(p);
        if (id >= tracepoint_count) {
            std::cerr << "bad tracepoint id " << id << "\n";
            return 1;
        }
        deserializers[id](p);
    }

    return 0;
}
)cpp";
    return code;
}

}  // namespace

std::string generate_decoder_source() {
    const std::span<const tracepoint_entry> table = tracepoints();

    // One column width for the whole run, so the output stays aligned.
    std::size_t fileline_width = 0;
    for (const tracepoint_entry& e : table) {
        fileline_width = std::max(fileline_width, std::format("{}:{}", e.file, e.line).size());
    }

    std::string out = generate_prologue();
    for (std::size_t i = 0; i < table.size(); ++i) {
        out += generate_deserializer(i, table[i], fileline_width);
    }
    out += generate_epilogue(table.size());
    return out;
}

}  // namespace tracer
