load("//buck:module.bzl", "add_module")

add_module(
    name = "trace_converter",
    srcs = [
        "converter.cc",
        "converter_test.cc",
    ],
    exported_headers = {
        "trace_converter/converter.h": "converter.h",
    },
    deps = [
        "//third-party:perfetto_protos",
        "//modules/trace-viewer:decoder",
        "//:doctest",
    ],
    compiler_flags = ["-Wall", "-Wextra"],
    module_source_dir = "modules/trace-converter",
)

cxx_binary(
    name = "trace_converter_bin",
    srcs = ["main.cc"],
    header_namespace = "",
    link_style = "static",
    deps = [":trace_converter", "//:doctest_impl"],
)
