# A demonstration that the vendored FuzzTest builds and fuzzes under Buck2.
#
# Build and run it in fuzzing mode with the `fuzztest` modifier, which turns on
# the sanitizer coverage the engine steers on and the ASan that turns a bad
# input into a detectable failure:
#
#     buck2 run //examples/fuzztest:rle_fuzz_test?fuzztest -- --seconds=60
#
# Without that modifier the binary still builds and links, but FuzzTest reports
# that it has no coverage instrumentation to work with.

cxx_library(
    name = "rle",
    srcs = ["rle.cc"],
    exported_headers = {"rle.h": "rle.h"},
    header_namespace = "",
    preferred_linkage = "static",
)

cxx_binary(
    name = "rle_fuzz_test",
    srcs = ["rle_fuzz_test.cc"],
    header_namespace = "",
    deps = [
        ":rle",
        "//:fuzztest_main",
        "fuzztest//fuzztest:fuzztest_core",
    ],
)
