load("//buck:module.bzl", "add_module")

export_file(
    name = "module_test_main",
    src = "module_test_main.cc",
    out = "module_test_main.cc",
    visibility = ["PUBLIC"],
)

cxx_library(
    name = "module_runner",
    srcs = ["module_run.cc"],
    exported_headers = {
        "module_run.h": "module_run.h",
    },
    exported_deps = ["//:doctest"],
    visibility = ["PUBLIC"],
)
